-- Keep the first time each user achieved a score. Later identical rows were
-- generated by the page-exit handler and must not restart rank celebrations.
WITH duplicates AS (
	SELECT
		id,
		ROW_NUMBER() OVER (
			PARTITION BY email, score
			ORDER BY created_at ASC, id ASC
		) AS duplicate_number
	FROM game_score_2048
)
DELETE FROM game_score_2048
WHERE id IN (
	SELECT id
	FROM duplicates
	WHERE duplicate_number > 1
);

CREATE UNIQUE INDEX "game_score_2048_email_score_key"
ON "game_score_2048"("email", "score");
