version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - dgst-mongo-net
    volumes:
      - dgst-mongo-vol:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=0719f132057c660a59a19c08af854d71
  dgst_svelte:
    image: dgst_svelte
    container_name: dgst_svelte
    restart: always
    build: .
    networks:
      - dgst-svelte-net
    volumes:
      - /Users/hunchulchoi/projects/volumes/dgst/uploads:/dgst/static/uploads
    ports:
      - '5173:4173'
    environment:
      NODE_ENV: production

networks:
  dgst-mongo-net:
  dgst-svelte-net:

volumes:
  dgst-mongo-vol:
  dgst-storage-vol:
