server{
 listen 80 default_server;
 server_name -;
 return 444;
}

server{
 listen 443 ssl default_server;
 server_name -;
 ssl_certificate /mnt/dgst/conf/private/2024/www_dgst.site_cert-2.pem;
 ssl_certificate_key /mnt/dgst/conf/private/2024/www_dgst.site-2.pem;

 return 444;
}
