export const BOARD_UPLOAD_MAX_BYTES = 100 * 1024 * 1024;
export const BOARD_UPLOAD_MAX_MB = BOARD_UPLOAD_MAX_BYTES / (1024 * 1024);
export const BOARD_UPLOAD_BODY_SIZE_LIMIT = `${BOARD_UPLOAD_MAX_MB}M`;
